#pragma once

#undef HAVE_DECL__SC_HOST_NAME_MAX
#define HAVE_INTTYPES_H 1
#undef HAVE_NETINET_IN_H
#define HAVE_SRANDOM 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#undef HAVE_SYS_FILE_H
#undef HAVE_SYS_IOCTL_H
#undef HAVE_SYS_SOCKET_H
#undef HAVE_SYS_TIME_H
#undef HAVE_UNISTD_H
#undef HAVE_USLEEP
#define PACKAGE_STRING "libuuid 1.0.3"
